name: Build Flutter Web for Cloudflare Pages

on:
  push:
    branches:
#      - master
      - test

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.1'

      - name: Enable Web
        run: flutter config --enable-web

      - name: Install Dependencies
        run: flutter pub get

      - name: Build Flutter Web
        run: flutter build web --release --base-href "/"

      - name: Save build output into temporary directory
        run: |
          mkdir -p /tmp/safe_build
          cp -r build/web/* /tmp/safe_build/

      - name: Checkout cloudflare-hosting branch
        run: |
          if git show-ref --verify --quiet refs/heads/cloudflare-hosting; then
            git checkout cloudflare-hosting
          else
            git checkout -b cloudflare-hosting
          fi

      - name: Replace contents with new build
        run: |
          rm -rf ./*
          cp -r /tmp/safe_build/* .
          git add .
          git commit -m "Cloudflare Pages build" || echo "No changes to commit"

      - name: Push cloudflare-hosting branch
        run: |
          git push origin cloudflare-hosting --force
